[package]
name = "e2e-example-bin"
version = "0.1.0"
edition.workspace = true
license = "0BSD"
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
camino.workspace = true
clap.workspace = true
dropshot-api-manager-types.workspace = true
dropshot-api-manager.workspace = true
e2e-example-apis.workspace = true
openapiv3.workspace = true
openapi-lint.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
