// Copyright 2026 Oxide Computer Company

//! Example API descriptions for the Dropshot API manager -- a couple of
//! examples, one that's lockstep and one that's versioned.

pub mod lockstep {
    use dropshot::{HttpError, HttpResponseOk, RequestContext};

    #[dropshot::api_description]
    pub trait LockstepApi {
        type Context;

        /// Get the value of the counter.
        #[endpoint { method = GET, path = "/counter" }]
        async fn get_counter(
            rqctx: RequestContext<Self::Context>,
        ) -> Result<HttpResponseOk<u32>, HttpError>;
    }
}

pub mod versioned {
    use dropshot::{HttpError, HttpResponseOk, Query, RequestContext};
    use dropshot_api_manager_types::api_versions;
    use schemars::JsonSchema;
    use serde::{Deserialize, Serialize};

    api_versions!([
        // Exercise: try uncommenting version 4 below. This will cause
        // the Dropshot API manager to generate a new OpenAPI document.
        // (5, FIVE_DOT_OH),
        // Version 4.0.0 adds an endpoint with query parameters, to test
        // detection of query parameter changes.
        (4, WITH_QUERY_PARAMS),
        // Version 3.0.0 was added to capture bytewise changes to the schema
        // serialization (e.g., the Number wrapper type being serialized as a
        // separate schema instead of inlined).
        (3, THREE_DOT_OH),
        (2, TWO_DOT_OH),
        (1, INITIAL),
    ]);

    #[dropshot::api_description]
    pub trait VersionedApi {
        type Context;

        /// Fetch `thing`
        #[endpoint {
            method = GET,
            path = "/thing",
            // Both get_thing_v1 and get_thing_v2 have the same `operation_id`,
            // which means that clients for each version generated by Progenitor
            // will use the same method name.
            operation_id = "get_thing",
            versions = "1.0.0"..VERSION_TWO_DOT_OH
        }]
        async fn get_thing_v1(
            rqctx: RequestContext<Self::Context>,
        ) -> Result<HttpResponseOk<ThingV1>, HttpError>;

        /// Fetch `thing`
        #[endpoint {
            method = GET,
            path = "/thing",
            // Both get_thing_v1 and get_thing_v2 have the same `operation_id`,
            // which means that clients for each version generated by Progenitor
            // will use the same method name.
            operation_id = "get_thing",
            versions = "2.0.0"..
        }]
        async fn get_thing_v2(
            rqctx: RequestContext<Self::Context>,
        ) -> Result<HttpResponseOk<ThingV2>, HttpError>;

        /// Search for items.
        ///
        /// This endpoint demonstrates query parameters for testing purposes.
        #[endpoint {
            method = GET,
            path = "/search",
            versions = VERSION_WITH_QUERY_PARAMS..
        }]
        async fn search(
            rqctx: RequestContext<Self::Context>,
            query_params: Query<SearchParams>,
        ) -> Result<HttpResponseOk<Vec<SearchResult>>, HttpError>;
    }

    #[derive(Serialize, JsonSchema)]
    struct ThingV1 {
        thing_str: &'static str,
        // EXERCISE: Comment out the line above, and uncomment the line below, to
        // introduce a breaking change to the blessed 1.0.0 version of this
        // API.
        // thing_number: u32,
    }

    #[derive(Serialize, JsonSchema)]
    struct ThingV2 {
        // Note: this was originally `thing_number: u32`, but a wrapper type was
        // added afterwards to test out wire-compatible changes to the schema.
        // This trivial change caused THREE_DOT_OH to be generated.
        thing_number: Number,
    }

    #[derive(Serialize, JsonSchema)]
    struct Number(u32);

    /// Query parameters for the search endpoint.
    #[derive(Deserialize, JsonSchema)]
    pub struct SearchParams {
        /// The search query string.
        pub query: String,
    }

    /// A search result item.
    #[derive(Serialize, JsonSchema)]
    pub struct SearchResult {
        /// The ID of the matching item.
        pub id: u64,
        /// The name of the matching item.
        pub name: String,
    }
}
